#!/usr/bin/env python3
"""One-off: cut the Phosphor icon font down to the icons this site actually uses.

Why: public/css/plugins.css carried all 9,162 icon rules for six weights (659 KB of the file's 936 KB) and the browser
downloaded 130-150 KB of woff2 for every weight used, for about 25 icons.

What it does (run from the project root, needs `pip install fonttools brotli`):
  1. collects every  ph-<name>  used in app/, components/, lib/ and public/js/app.js
  2. keeps three weights (regular, fill, bold: the only ones used) and subsets each font to those glyphs
        -> public/fonts/phosphor.woff2, phosphor-fill.woff2, phosphor-bold.woff2  (a few KB each)
  3. writes public/css/icons.css (the @font-face + .ph / .ph-fill / .ph-bold rules + one :before rule per icon)
  4. removes the whole "Phosphor Icons" section from public/css/plugins.css

The original fonts stay in public/fonts/Phosphor/ (unreferenced afterwards) so this can be re-run when an icon is added:
add the class in the code, run the script again (step 4 is skipped once the section is gone; it then only refreshes 1-3
from the original font files and the icon map in scripts/phosphor-map.json).
"""
import json, re, subprocess, sys
from pathlib import Path

ROOT = Path(".")
CSS = ROOT / "public/css/plugins.css"
MAP = ROOT / "scripts/phosphor-map.json"          # {"regular": {"name": "e000"}, "fill": {...}, "bold": {...}}
SRC_FONTS = {"regular": "Phosphor", "fill": "Phosphor-Fill", "bold": "Phosphor-Bold"}
OUT_FONTS = {"regular": "phosphor", "fill": "phosphor-fill", "bold": "phosphor-bold"}
FAMILY = {"regular": "Phosphor", "fill": "Phosphor-Fill", "bold": "Phosphor-Bold"}
CLASS = {"regular": "ph", "fill": "ph-fill", "bold": "ph-bold"}

# ---- 1. icons in use
used = set()
for base in ("app", "components", "lib"):
    for p in (ROOT / base).rglob("*"):
        if p.suffix in (".tsx", ".ts"):
            used |= set(re.findall(r"\bph-([a-z0-9]+(?:-[a-z0-9]+)*)", p.read_text(encoding="utf-8")))
used |= set(re.findall(r"\bph-([a-z0-9]+(?:-[a-z0-9]+)*)", (ROOT / "public/js/app.js").read_text(encoding="utf-8")))
weights = {"bold", "fill", "light", "thin", "duotone", "regular"}
used = sorted(u for u in used if u not in weights)
print(f"{len(used)} icons in use:", ", ".join(used))

# ---- icon -> code point, per weight (read once from the original CSS, then cached in scripts/phosphor-map.json)
css = CSS.read_text(encoding="utf-8")
if MAP.exists():
    glyphs = json.loads(MAP.read_text())
else:
    glyphs = {}
    for w, cls in CLASS.items():
        rx = re.compile(r"^\." + re.escape(cls) + r"\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\";", re.M)
        glyphs[w] = {n: c.lower() for n, c in rx.findall(css)}
    MAP.write_text(json.dumps(glyphs, indent=0))
missing = [(w, n) for w in CLASS for n in used if n not in glyphs[w]]
if missing:
    sys.exit(f"icons missing from the font: {missing}")

# ---- 2. subset the fonts
for w in CLASS:
    unicodes = ",".join("U+" + glyphs[w][n] for n in used)
    src = ROOT / f"public/fonts/Phosphor/{SRC_FONTS[w]}.woff2"
    out = ROOT / f"public/fonts/{OUT_FONTS[w]}.woff2"
    subprocess.run(["pyftsubset", str(src), f"--unicodes={unicodes}", "--flavor=woff2", "--layout-features=", f"--output-file={out}"], check=True)
    print(f"{out.name:22} {src.stat().st_size // 1024:4d} KB -> {out.stat().st_size / 1024:5.1f} KB")

# ---- 3. icons.css
BASE = """  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: "%s" !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  letter-spacing: 0;
  -webkit-font-feature-settings: "liga";
          font-feature-settings: "liga";
  -webkit-font-variant-ligatures: discretionary-ligatures;
          font-variant-ligatures: discretionary-ligatures;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
"""
parts = ["/* Phosphor icons, cut down to the icons the site uses (generated by scripts/build-icons.py: do not edit by hand). */"]
for w in CLASS:
    parts.append('@font-face {\n  font-family: "%s";\n  src: url("../fonts/%s.woff2") format("woff2");\n  font-weight: normal;\n  font-style: normal;\n  font-display: block;\n}' % (FAMILY[w], OUT_FONTS[w]))
    parts.append(".%s {\n%s}" % (CLASS[w], BASE % FAMILY[w]))
    for n in used:
        parts.append('.%s.ph-%s:before {\n  content: "\\%s";\n}' % (CLASS[w], n, glyphs[w][n]))
(ROOT / "public/css/icons.css").write_text("\n".join(parts) + "\n", encoding="utf-8")

# ---- 4. strip the section from plugins.css (once)
a = css.find("/* ------------------------------------------------*/\n/* Phosphor Icons Start */")
b = css.find("/* Phosphor Icons End */")
if a != -1 and b != -1:
    b_end = css.index("\n", css.index("/* ------------------------------------------------*/", b)) + 1
    new = css[:a] + css[b_end:]
    CSS.write_text(new, encoding="utf-8")
    print(f"plugins.css {len(css) // 1024} KB -> {len(new) // 1024} KB")
else:
    print("plugins.css already stripped")
